# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_graphWindow(object):
    def setupUi(self, Dialog_graphWindow):
        Dialog_graphWindow.setObjectName("Dialog_graphWindow")
        Dialog_graphWindow.resize(991, 550)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog_graphWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog_graphWindow)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog_graphWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_graphWindow)

    def retranslateUi(self, Dialog_graphWindow):
        _translate = QtCore.QCoreApplication.translate
        Dialog_graphWindow.setWindowTitle(_translate("Dialog_graphWindow", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_graphWindow", "Rtt"))
