# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip_list_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 35)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(450, 35))
        Dialog.setMaximumSize(QtCore.QSize(1000, 35))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 446, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username = QtWidgets.QVBoxLayout()
        self.username.setObjectName("username")
        self.lineEdit_ipaddres = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ipaddres.setStyleSheet("border: none;\n"
"background: transparent;\n"
"")
        self.lineEdit_ipaddres.setText("")
        self.lineEdit_ipaddres.setReadOnly(True)
        self.lineEdit_ipaddres.setObjectName("lineEdit_ipaddres")
        self.username.addWidget(self.lineEdit_ipaddres)
        self.horizontalLayout.addLayout(self.username)
        self.ip_addres = QtWidgets.QVBoxLayout()
        self.ip_addres.setObjectName("ip_addres")
        self.lineEdit_username = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_username.setStyleSheet("border: none;\n"
"background: transparent;\n"
"")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setReadOnly(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.ip_addres.addWidget(self.lineEdit_username)
        self.horizontalLayout.addLayout(self.ip_addres)
        self.password = QtWidgets.QVBoxLayout()
        self.password.setObjectName("password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setStyleSheet("border: none;\n"
"background: transparent;\n"
"")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setReadOnly(True)
        self.lineEdit_password.setClearButtonEnabled(False)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.password.addWidget(self.lineEdit_password)
        self.horizontalLayout.addLayout(self.password)
        self.pushButton_del = QtWidgets.QPushButton(Dialog)
        self.pushButton_del.setGeometry(QtCore.QRect(550, 6, 61, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_del.setIcon(icon)
        self.pushButton_del.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_connect = QtWidgets.QPushButton(Dialog)
        self.pushButton_connect.setGeometry(QtCore.QRect(448, 6, 101, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/phone-call.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_connect.setIcon(icon1)
        self.pushButton_connect.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_connect.setObjectName("pushButton_connect")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_del.setText(_translate("Dialog", "Del"))
        self.pushButton_connect.setText(_translate("Dialog", "Connect to"))
import resources_rc
