# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sshClient_summaryi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 37)
        Dialog.setMinimumSize(QtCore.QSize(319, 37))
        Dialog.setMaximumSize(QtCore.QSize(319, 37))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 320, 38))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(24, 24))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/ubuntulogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.left = QtWidgets.QWidget(self.widget)
        self.left.setMaximumSize(QtCore.QSize(91, 36))
        self.left.setObjectName("left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.left)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_username = QtWidgets.QLineEdit(self.left)
        self.lineEdit_username.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_username.setReadOnly(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_2.addWidget(self.lineEdit_username)
        self.horizontalLayout.addWidget(self.left)
        self.right = QtWidgets.QWidget(self.widget)
        self.right.setMaximumSize(QtCore.QSize(159, 36))
        self.right.setObjectName("right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.right)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_hostname = QtWidgets.QLineEdit(self.right)
        self.lineEdit_hostname.setReadOnly(True)
        self.lineEdit_hostname.setObjectName("lineEdit_hostname")
        self.verticalLayout_3.addWidget(self.lineEdit_hostname)
        self.horizontalLayout.addWidget(self.right)
        self.pushButton_more = QtWidgets.QPushButton(self.widget)
        self.pushButton_more.setMaximumSize(QtCore.QSize(39, 31))
        self.pushButton_more.setStyleSheet("QPushButton {\n"
"    padding-top: 20px;\n"
"    padding-bottom: 20px;\n"
"    writing-mode: vertical-rl;  /* Sağdan sola dikey yazı */\n"
"    text-orientation: mixed;    /* Harfler yan döner */\n"
"}")
        self.pushButton_more.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_more.setIcon(icon)
        self.pushButton_more.setObjectName("pushButton_more")
        self.horizontalLayout.addWidget(self.pushButton_more)
        self.pushButton_close = QtWidgets.QPushButton(self.widget)
        self.pushButton_close.setMaximumSize(QtCore.QSize(16, 25))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "User Name"))
        self.label_3.setText(_translate("Dialog", "Host Name"))
        self.pushButton_close.setText(_translate("Dialog", "X"))
import resources_rc
